version: '3.3'

services:
  postgres:
    image: postgres:9.6.17
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${POSTGRESQL_PASS}

      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
    image: jboss/keycloak:12.0.2
    ports:
      - "18080:8080"
    restart: always
    networks:
      - local-keycloak

  oauth2-proxy:
    image: docker.io/bitnami/oauth2-proxy:6-debian-10
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: 32D1Fr7mcd2s6kpx
      OAUTH2_PROXY_EMAIL_DOMAINS: marcelkoch.net
      OAUTH2_PROXY_PROVIDER: keycloak
      OAUTH2_PROXY_CLIENT_ID: keycloak
      OAUTH2_PROXY_CLIENT_SECRET: keycloak
      OAUTH2_PROXY_LOGIN_URL: http://keycloak/realms/marcelkoch.net/protocol/openid-connect/auth"
      OAUTH2_PROXY_REDEEM_URL: http://keycloak/realms/marcelkoch.net/protocol/openid-connect/token"
      OAUTH2_PROXY_VALIDATE_URL: http://keycloak/realms/marcelkoch.net/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_KEYCLOAK_GROUP: keycloak
    ports:
      - '28080:8080'
      - '24180:4180'

networks:
  local-keycloak: